# This is a basic workflow to help you get started with Actions

name: Continuous Integration

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    if: github.repository == 'ml4ai/tomcat-planrec'
    strategy:
      matrix:
        os: [ubuntu-22.04]


    steps:
    - uses: actions/checkout@v2
    - name: Continuous Integration
      run: |
        # We download Boost 1.79 separately since apt does not have the minimum
        # version of Boost we require (as of August 18th, 2022).
        sudo ./scripts/install_boost_from_source
        sudo apt-get update
        sudo apt-get install -y nlohmann-json3-dev graphviz libgraphviz-dev libz3-dev libpaho-mqtt-dev libpaho-mqttpp-dev
        sudo apt-get install -f
        mkdir build
        cd build
        cmake .. 
        make -j
        make test
