# This is a basic workflow to help you get started with Actions

name: Continuous Integration

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    if: github.repository == 'ml4ai/tomcat-planrec'
    strategy:
      matrix:
        os: [ubuntu-20.04]


    steps:
    - uses: actions/checkout@v2
    - name: Install Boost
      uses: MarkusJx/install-boost@v1.0.1
      with:
        boost_version: 1.76.0
    - name: Continuous Integration
      run: |
        sudo apt-get install nlohmann-json3-dev libgraphviz-dev
        mkdir build
        cd build
        cmake .. 
        make -j
        make test
