# This is a basic workflow to help you get started with Actions

name: Continuous Integration

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    if: github.repository == 'ml4ai/tomcat-planrec'
    strategy:
      matrix:
        os: [ubuntu-20.04]


    steps:
    - uses: actions/checkout@v2
    - name: Continuous Integration
      run: |
        # We download Boost 1.76 separately since apt does not have the minimum
        # version of Boost we require (as of July 20, 2021).
        ./scripts/install_boost_from_source
        sudo apt-get install -y nlohmann-json3-dev graphviz libgraphviz-dev libz3-dev
        mkdir build
        cd build
        cmake .. 
        make -j
        make test
